spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  level:
    root: warn
    com.yclouds: debug
mybatis-plus:
  type-enums-package: com.yclouds.demo.mybatisplus.enums
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
  mapper-locations: classpath*:mappings/*.xml

